{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.smartconnect",
    "module": "smartsip-sdk",
    "version": "0.0.84",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4.114"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.84.aar",
          "url": "smartsip-sdk-0.0.84.aar",
          "size": 73049,
          "sha512": "374c6b0941400fa239a5505185dbaf3c60b53211eeccc0180756f8a044b88f18d44870579e82620af44d39410661b6bdacc2d235e4c5cd0667ef2d4a7cd7d12e",
          "sha256": "e570254608747e983b446aeaf521f9e1f9dd5e034fcf9c844438de875e024ee1",
          "sha1": "657b51a1d6b2b96e014385f1404e516eb7243b9a",
          "md5": "9d0a050bad998ccf4741ad174139c141"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4.114"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.84.aar",
          "url": "smartsip-sdk-0.0.84.aar",
          "size": 73049,
          "sha512": "374c6b0941400fa239a5505185dbaf3c60b53211eeccc0180756f8a044b88f18d44870579e82620af44d39410661b6bdacc2d235e4c5cd0667ef2d4a7cd7d12e",
          "sha256": "e570254608747e983b446aeaf521f9e1f9dd5e034fcf9c844438de875e024ee1",
          "sha1": "657b51a1d6b2b96e014385f1404e516eb7243b9a",
          "md5": "9d0a050bad998ccf4741ad174139c141"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smartsip-sdk-0.0.84-javadoc.jar",
          "url": "smartsip-sdk-0.0.84-javadoc.jar",
          "size": 354312,
          "sha512": "1f895906d43a563700214cbbfb37401eec2b05bf90c04b58607dfbf345c59f4c966b1a7324af92665507b022cf71cef229d8411156e936d99db9c139bf49443a",
          "sha256": "7249e40ea959830247cced5bcb66b0e9dd9adb06b70748a6ee5b03b8292f8274",
          "sha1": "cc4f6b3528582735dcba39f5c3d5ec954b953771",
          "md5": "fb95247d05ec59b8093c654755b936ee"
        }
      ]
    }
  ]
}
