{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.smartconnect",
    "module": "smartsip-sdk",
    "version": "0.0.79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4+"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.79.aar",
          "url": "smartsip-sdk-0.0.79.aar",
          "size": 62468,
          "sha512": "7a89842ba603ee46ad58a4c7e90978f00fe392ac38ef0028b99a0539399a259aedc087246c8c7bcd9782b590ee45a0e51a18af0b5347c6a9b18208bb0ec2b8b8",
          "sha256": "ea7a7f84635729a543f8db29f1a045b7ff1eff9aa61c6292d54d8f52a68e3bbb",
          "sha1": "7fc8f8dbd37642c33c767a98bf90c93551cdbebc",
          "md5": "ee7cba5295ec58fad96dc00c08c94a1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4+"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.79.aar",
          "url": "smartsip-sdk-0.0.79.aar",
          "size": 62468,
          "sha512": "7a89842ba603ee46ad58a4c7e90978f00fe392ac38ef0028b99a0539399a259aedc087246c8c7bcd9782b590ee45a0e51a18af0b5347c6a9b18208bb0ec2b8b8",
          "sha256": "ea7a7f84635729a543f8db29f1a045b7ff1eff9aa61c6292d54d8f52a68e3bbb",
          "sha1": "7fc8f8dbd37642c33c767a98bf90c93551cdbebc",
          "md5": "ee7cba5295ec58fad96dc00c08c94a1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smartsip-sdk-0.0.79-javadoc.jar",
          "url": "smartsip-sdk-0.0.79-javadoc.jar",
          "size": 349438,
          "sha512": "66d99af2b5d1844f4ca6923854e798d06f3728be91f5c4992745ff2be9e75bd4f8754fc42d62fbfe132c904da27da5d4de8b487759d0b9c714942c1d302a63eb",
          "sha256": "a87de168dccca1eb3404292d5c6906ab0d463f2a7ededd4d2004f032bec7f9ec",
          "sha1": "2f297595b3dababf00179032e50e91587a8c8b30",
          "md5": "da7d616defe8180d0387b085eb007c29"
        }
      ]
    }
  ]
}
