{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.smartconnect",
    "module": "smartsip-sdk",
    "version": "0.0.93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4.114"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.93.aar",
          "url": "smartsip-sdk-0.0.93.aar",
          "size": 84957,
          "sha512": "6aebf30acef0bd5d3dab776b42d094384f8095f80378fd4057020fa7fc0ae4f37550d52878ebdc7478f78031942896c728f755093781882fd866aaa666748e88",
          "sha256": "664e6e946aa2c817dd9e92e8e207545ed9386502b4ae8698711fd690acc8d3c7",
          "sha1": "e809d18e7b29385d1953037f7c44a19697435a84",
          "md5": "a18c360fba9d2dbc649ea285f17292ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.linphone.bundled",
          "module": "linphone-sdk-android",
          "version": {
            "requires": "5.4.114"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartsip-sdk-0.0.93.aar",
          "url": "smartsip-sdk-0.0.93.aar",
          "size": 84957,
          "sha512": "6aebf30acef0bd5d3dab776b42d094384f8095f80378fd4057020fa7fc0ae4f37550d52878ebdc7478f78031942896c728f755093781882fd866aaa666748e88",
          "sha256": "664e6e946aa2c817dd9e92e8e207545ed9386502b4ae8698711fd690acc8d3c7",
          "sha1": "e809d18e7b29385d1953037f7c44a19697435a84",
          "md5": "a18c360fba9d2dbc649ea285f17292ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smartsip-sdk-0.0.93-javadoc.jar",
          "url": "smartsip-sdk-0.0.93-javadoc.jar",
          "size": 355262,
          "sha512": "e7de72c3467e74ed74ec0da55c53cd85a0faddfd256c65fe1a7d521e37f066e968137b5c156aa6159d4b03fe513879a1cf24b5492129e22a56f019aabd9f4a51",
          "sha256": "f883f6c130fc9292e1145ee0d91416bc7776f2a116f786080ae760f8cbc571fd",
          "sha1": "e766beeaa669df7a429628a87f85c39c8f5c8af6",
          "md5": "b8de3fdca057784b40bf21e03e594a9f"
        }
      ]
    }
  ]
}
